services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
  frontend:
    container_name: frontend
    image: "node:14-alpine"
    user: "node"
    working_dir: /cia
    volumes: 
      - ./cia:/app/cia
    command:  "yarn install  && yarn start"
    depends_on:
      - web
    ports:
      - "3001:3001"
version: '3'